### ISSUE TITLE
Update dockerfile to include the following steps in dataset setup

### ISSUE THREAD

**Issue by raresito** [unibuc-cs/IoT-Dataset-Dockerized#5]
From the [vision document](https://docs.google.com/document/d/1mAzhIEgPqoXQrcMG3zWo8FYKWIHcyZpSLVTvhs32KaQ/edit), this docker file should also implement the following steps:

- Create openapi-api-client for every project in the dataset
- Create base app.py for each open-api-client project (can be extracted from the README.md created by the generator for each app)
- Build and install each openapi-api-client as a python package
- Build and run every app in the dataset
- Run application-hub’s app.py

If these steps are more complex than anticipated, this issue should be split into multiple issues.

**Comment by JustBeYou** [comment]
Done
